stages:
  - build
  - test
  - security-test
  - deploy
  

include:
  - local: '/GamePlatformContext/game-context-gitlab-ci.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH == "main"
        changes:
           - 'GamePlatformContext/**/*'
  
  - local: '/CheckersContext/checkers-context-gitlab-ci.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH == "main"
        changes:
           - 'CheckersContext/**/*'
  
  - local: '/StatisticsContext/statistics-context-gitlab-ci.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH == "main"
        changes:
           - 'StatisticsContext/**/*'


merge-test:
  stage: test
  script:
    - exit 0
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"